title: My Home Page
author: zehrayelkenci
email: zehrayelkenci03@gmail.com
description: > # my personal information
education
projects

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  zehrayelkenci # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
